version: '3.3'

services:
  app:
    container_name: docker_express
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - PORT=3000
    command: npm start
volumes:
 node_modules: